<template>
  <div class="wobble">
    <client-only>
      <marquee-text id="marquee" class="pt-6 pb-10 -mt-2" @mouseover="marqueePaused = true" @mouseleave="marqueePaused = false" :duration="400" :paused="marqueePaused">
        <span class="marquee-text PicNic">
          &nbsp;&nbsp;&nbsp;&nbsp;
          The gut goes all the way from your head to your bottom...
          0.18g of CO2 was used to load this website...
          Club night announcement coming soon...
          Budgets, assets, interviews, templates, funding + licensing applictions, more assets, more budgets...
          Get into our guts...
          This domain cost $95.80 for 5 years...
          Lots of people have visited this site but you are our fave...
          French Street Studios...
          J******* W*****...
          P*** F*****...
          H*****...
          Funded by NUMBERS X YOUTH MUSIC...
          Bleep bloop...
          OOOWWWWWCCCHHH I stubbed my toe!...
          This message is made up of 40 characters...
            </span>
      </marquee-text>
    </client-only>
  </div>
</template>

<script>
export default {
  data() {
    return {
      marqueePaused: false,
    }
  },
}
</script>

<style scoped>
  .wobble {
    background-image: url('~assets/img/wobble.svg');
    background-repeat: no-repeat;
    background-position: bottom;
    background-size: cover;
  }
</style>